整理券の待ち人数を表示
winkichanwi/training2018-final-project pull request #9
Opened 2018-07-10 09:34 UTC by winkichanwi

## やったこと
（featureごとでcommitを忘れてしまたため結構混ざっていてすみません）
- [x] 整理券を種類ごと数をcountするAPIの実装
- [x] レストラン一覧の画面で整理券待ち人数を表示するcomponentを作成
- [x] 上記のcomponentがAPIにrequestしデータを表示できるようにする
- [x] ちょっとコードの改善することしている
- [x] 画面の改善することもしている

## ノート
（まだやっていないところ）
- [x] API側のエラーハンドラー
- [x] フロント側のエラーメッセージを表示
- [x] ログインのセッションの確認

2018-07-11 06:13 UTC, xoyo24 requested changes
全体的に、
- PRが大きいので、もっと細かく分割して出しましょう。
- 前のPRのコメントが直してない部分があるので、いつ直す予定でしょうか？どこで管理してますか？

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/restaurant-list/restaurant-list.component.ts
> +  private getListOfRestaurants() {
こちらのエラー処理はないですか？

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/services/user.service.ts
> +export class UserSignup {
interface と class はどうな使い分けをしていますか？
あと、このファイル以外でも利用しているなら、ファイルを分けたほうがいいかもしれません。

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/signup/signup.component.ts
> +  loading = false;
Boolean なら, isLoading がいいです。

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/signup/signup.component.ts
> +  signupJson: any;
```
private signUp(signupJson: any) {
  ...
}
```
みたいな感じにすると、もっと汎用的になるし、ここも定義しなくてもいいと思います。

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/ticker-reservation/ticker-reservation.component.ts
> +  loading = false;
isLoading がいいと思います。

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/ticker-reservation/ticker-reservation.component.ts
> +    console.log('Session');
console.log は最後全部消しましょう。

2018-07-11 06:13 UTC, xoyo24 commented on restaurant-remote-reception-app/src/app/ticker-reservation/ticker-reservation.component.ts
> +    this.sessionToken = this.cookieService.get('user-id');
ログに出す以外使ってないですか？

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception-app/src/app/ticker-reservation/ticker-reservation.component.ts
> +  seatNo = 0;
Angular の状態管理はどうなっているのがよくわからないが、この辺減らせるなら少ない状態を保持するほうがシンプルかつ安全と思います。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception-app/src/environments/environment.prod.ts
> +  API_HOST: 'http://18.179.49.225'
IPが変わるかもしれないので、Domain名を使いましょう。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/RestaurantController.scala
> +        def queryRestaurantsByShoppingCenterId =
必要ないなら、メソードの中メソードを作らない方がいいと思います

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/RestaurantController.scala
> +    def get(restaurantId: Int) = Action.async { implicit rs =>
ユーザーがログイン中かどうかはチェック必要ですね。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/RestaurantController.scala
>      def list(shoppingCenterId: Int) = Action.async { implicit rs =>
ユーザーがログイン中かどうかはチェック必要ですね。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/TicketController.scala
> +    private val activeTicketStatusSeq: Seq[String] = TicketStatus.values.filter(_.isActive).map(value => value.toString).toSeq
`Seq(TicketStatus.ACTIVE, TicketStatus.CALLED)` のほうがわかりやすいと思います。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/TicketController.scala
> +    private val activeTicketStatusSeq: Seq[String] = TicketStatus.values.filter(_.isActive).map(value => value.toString).toSeq
一回しか使わないなら、メソードの中で定義するほうがいいと思います。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/TicketController.scala
> +        def queryTicketCounts = for {
2回 for 使っていますが、一個にまとまってください。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/UserController.scala
> +class UserController @Inject()(val dbConfigProvider: DatabaseConfigProvider)(cache: CacheApi)(implicit ec: ExecutionContext)
cacheApi はどこで使っていますか？

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/TicketController.scala
> +object TicketController {
Controller は Singleton なので、companion object は作る必要ないです。

2018-07-11 06:13 UTC, xiaoyang24 commented on restaurant-remote-reception/app/controllers/TicketController.scala
> +object TicketController {
RestaurantTicketCounts を独立するほうがいいと思います。

2018-07-11 06:13 UTC, xiaoyang24 commented
ちなみに、承認しないと、Mergeできないように設定してもらいますか？

2018-07-18 04:53 UTC, xiaoyang24 commented on README.md
> + $ docker run --env APPLICATION_SECRET={} --env ALLOWED_ORIGINS_1={} --env MYSQL_DATABASE_URL={} --env MYSQL_DATABASE_USER={} --env MYSQL_DATABASE_PWD={} -p 9000:9000 restaurant-remote-reception:late
`ALLOWED_ORIGINS_1` 一つに限定するなら、 `ALLOWED_ORIGIN` でいいと思います。

2018-07-18 04:53 UTC, xiaoyang24 commented on restaurant-remote-reception-app/src/app/user-login/user-login.component.ts
>      this.loginJson = JSON.stringify(this.user);
こちらも `this.login()` のパラメーターとして渡したほうがいいかもしれませんね

2018-07-18 04:53 UTC, xiaoyang24 commented on restaurant-remote-reception/build.sbt
> +libraryDependencies += cache
どこで使う予定ですか？

2018-07-18 04:53 UTC, xiaoyang24 commented on restaurant-remote-reception-app/src/app/services/user.service.ts
> +  public getMe() {
ここは `getCurrentUserInfo` がもっとわかりやすいかも。

2018-07-18 07:35 UTC, winkichanwi commented on restaurant-remote-reception/build.sbt
> +libraryDependencies += cache
消しのに忘れてしまいました、すみません。

2018-07-18 07:36 UTC, winkichanwi commented on restaurant-remote-reception-app/src/app/services/user.service.ts
> +  public getMe() {
そうですね、ありがとうございます。

2018-07-18 07:55 UTC, xoyo24 approved these changes

2018-07-18 08:07 UTC, merged